core/accounts/urls.py
from django.urls import path, include
from .views import CustomLoginView, RegisterPage

from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(next_page="/"), name="logout"),
    path("register/", RegisterPage.as_view(), name="register"),
    path("api/", include("accounts.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from todo.api.v1.views import weatherView

from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)


schema_view = get_schema_view(
    openapi.Info(
        title="TODO app apis",
        default_version="v1",
        description="this api documentation is for maktabkhooneh homework",
        terms_of_service="",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path('weather/',weatherView, name='weather'),
    path("api-auth/", include("rest_framework.urls")),
    path("accounts/", include("accounts.urls")),
    path("todo/", include("todo.urls")),
    # doc
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    # drf-spec
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    path(
        "schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"
    ),
]

core/todo/api/v1/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from . import views

app_name = "api-v1"

router = DefaultRouter()

router.register("task", views.TaskViewSet, basename="task")
urlpatterns = []
urlpatterns += router.urls

core/todo/urls.py
from django.urls import include, path
from . import views


app_name = "todo"


urlpatterns = [
    path("", views.TaskListView.as_view(), name="task-list"),
    path("create/", views.TaskCreateView.as_view(), name="task-create"),
    path("update/<int:pk>/", views.TaskUpdateView.as_view(), name="task-update"),
    path("delete/<int:pk>/", views.TaskDeleteView.as_view(), name="task-delete"),
    path("complete/<int:pk>/", views.TaskCompleteView.as_view(), name="task-complete"),
    path("apis/", include("todo.api.v1.urls")),
]

core/todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Task(models.Model):
    """
    this models just holds a title of task for todo app
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    completed = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        order_with_respect_to = "user"

    def get_username(self):
        return self.user.username

    def __str__(self):
        return self.title

core/todo/forms.py
from django import forms
from .models import Task


class TaskUpdateForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control rounded-4",
                "name": "title",
                "placeholder": "enter the title",
            }
        ),
        label="",  # when it take a value here, it will overlap
    )

    class Meta:
        model = Task
        fields = ("title",)

core/todo/api/v1/views.py
import requests
from rest_framework.viewsets import ModelViewSet
from django.http import JsonResponse
from django_filters.rest_framework import DjangoFilterBackend
from django.views.decorators.cache import cache_page
from rest_framework.filters import SearchFilter
from rest_framework.permissions import IsAuthenticated

from todo.models import Task
from .serializers import TaskSerializer
from .permissions import IsOwner


class TaskViewSet(ModelViewSet):
    serializer_class = TaskSerializer
    permission_classes = [IsAuthenticated, IsOwner]
    filter_backends = [
        DjangoFilterBackend,
    ]
    filterset_fields = ["title", "completed"]

    def get_queryset(self):
        tasks = Task.objects.filter(user=self.request.user)
        return tasks

@cache_page(60*20)
def weatherView(request):
    weather_data = requests.get('https://api.openweathermap.org/data/2.5/weather?lat=35.700&lon=51.39&appid=caf1619dcd9cd26660c98eca593f0b31')
    return JsonResponse(weather_data.json())

core/todo/views.py
from django.db.models.query import QuerySet
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import View

from todo.forms import TaskUpdateForm
from .models import Task


# Create your views here.


class TaskListView(LoginRequiredMixin, ListView):
    """
    CBV for listing user tasks
    """

    model = Task
    context_object_name = "tasks"
    template_name = "todo/todo_list.html"

    def get_queryset(self):

        return Task.objects.filter(user=self.request.user)


class TaskCreateView(LoginRequiredMixin, CreateView):
    """
    a CBV for creating new task in todo app
    """

    model = Task
    fields = ("title",)
    success_url = reverse_lazy("todo:task-list")
    template_name = "todo/update_task.html"
    # form_class = TaskForm      # it could be, it's not wrong

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)  # do we really need to give super() values??


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    """
    updated task based on TaskUpdateForm and redirects to list of tasks
    """

    model = Task
    success_url = reverse_lazy("todo:task-list")
    form_class = TaskUpdateForm
    template_name = "todo/update_task.html"


class TaskCompleteView(LoginRequiredMixin, View):
    """
    changes status of user Tasks and redirects back to main page(task list)
    """

    model = Task
    success_url = reverse_lazy("todo:task-list")

    def get(self, request, *args, **kwargs):
        """
        specifies what url does when request is GET
        """
        obj = Task.objects.get(id=kwargs.get("pk"))
        obj.completed = True  # complete => completed
        obj.save()
        return redirect(self.success_url)


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    """
    Deletes Task and redirects to list of tasks(makes sure that users only delete their own tasks)
    """

    model = Task
    context_object_name = (
        "task"  # the name of object that will be used in html template {{task}}
    )
    success_url = reverse_lazy("todo:task-list")
    template_name = "todo/task_delete.html"

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

core/todo/templates/todo/task_delete.html
{% extends "base.html" %}

{% block content %}
<p>Are you sure you want to delete this masterpiece?!
   -   {{task}}
</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm">

</form>
{% endblock content %}

core/todo/templates/todo/todo_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Task {% endblock %}
{% block extra_css %}
{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
	<div class="modal-dialog" role="document">
		<div class="modal-content rounded-5 shadow">
			<div class="modal-header p-5 pb-4 border-bottom-0">
				<!-- <h5 class="modal-title">Modal title</h5> -->
				<h2 class="fw-bold mb-0">Edit Form</h2>
				<a type="button" class="btn-close" href="{% url 'task_list' %}"></a>
			</div>

			<div class="modal-body p-5 pt-0">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="form-floating mb-3">						
                        {{form}}
						<label for="floatingInput">Title</label>
					</div>
					<button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Change</button>
				</form>				
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

<div class="header-bar">
    <a href="{% url 'tasks' %}">&#8592; Back</a>
</div>


<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Submit">
    </form>
</div>

core/todo/templates/todo/todo_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Todo List {% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-5 shadow">
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <!-- <h5 class="modal-title">Modal title</h5> -->
        <h2 class="fw-bold mb-0">Todo App</h2>
        <a type="button" class="btn-close" href="{% url 'accounts:logout' %}"></a>
        <!-- Logout button is not obvious enough -->
      </div>

      <div class="modal-body p-5 pt-0">

        <form class="pt-3" method="POST" action="{% url 'todo:task-create' %}">
          {% csrf_token %}
          <div class="input-group mb-3">
            <input type="text" class="form-control rounded-4" name="title" placeholder="Enter task title"
              aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-primary" type="submit">Add</button>
          </div>


          <hr class="my-4">
          {% for task in tasks %}
          <div class="input-group py-1">
            <span type="text" class="form-control" aria-label="Text input with segmented dropdown button">
              {% if task.complete == True %}
              <strike>{{task.title}}</strike>
              {% else %}
              <span>{{task}}</span>
              {% endif %}
            </span>
            <a type="button" class="btn btn-danger" href="{% url 'todo:task-delete' task.id %}"><i class="bi bi-trash"></i></a>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
              aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><a class="dropdown-item" href="{% url 'todo:task-complete' task.id %}">Done</a></li>
              <li><a class="dropdown-item" href="{% url 'todo:task-update' task.id %}">Edit</a></li>
            </ul>
          </div>
      
          {% endfor %}          
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

core/todo/templates/todo/update_task.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Task {% endblock %}
{% block extra_css %}
{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
	<div class="modal-dialog" role="document">
		<div class="modal-content rounded-5 shadow">
			<div class="modal-header p-5 pb-4 border-bottom-0">
				<!-- <h5 class="modal-title">Modal title</h5> -->
				<h2 class="fw-bold mb-0">Edit Form</h2>
				<a type="button" class="btn-close" href="{% url 'todo:task-list' %}"></a>
			</div>

			<div class="modal-body p-5 pt-0">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="form-floating mb-3">						
                        {{form}}
						<label for="floatingInput">Title</label>
					</div>
					<button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Change</button>
				</form>				
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

<div class="header-bar">
    <a href="{% url 'todo:task-list' %}">&#8592; Back</a>
</div>


<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Submit">
    </form>
</div>